"""update users table

Revision ID: 0339f6ed7ef5
Revises: b2d9d97be405
Create Date: 2026-01-27 13:07:07.187827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0339f6ed7ef5'
down_revision: Union[str, Sequence[str], None] = 'b2d9d97be405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_pin')
    # ### end Alembic commands ###
