"""add is_admin in group-members

Revision ID: 8137db43b1cc
Revises: 36a5f4b69d99
Create Date: 2026-01-07 23:15:40.982971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8137db43b1cc'
down_revision: Union[str, Sequence[str], None] = '36a5f4b69d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'is_admin')
    # ### end Alembic commands ###
