"""update expense table

Revision ID: 8702b44c419a
Revises: ae7446606725
Create Date: 2026-01-13 18:39:04.079039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8702b44c419a'
down_revision: Union[str, Sequence[str], None] = 'ae7446606725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_paid_by_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'group_members', ['paid_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_paid_by_fkey'), 'expenses', 'users', ['paid_by'], ['id'])
    # ### end Alembic commands ###
