"""update expense table

Revision ID: 9c6454b33650
Revises: 8137db43b1cc
Create Date: 2026-01-13 16:56:09.870363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6454b33650'
down_revision: Union[str, Sequence[str], None] = '8137db43b1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('strategy', sa.String(), server_default='equal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'strategy')
    # ### end Alembic commands ###
