"""update expense table

Revision ID: ae7446606725
Revises: bbf3798d3401
Create Date: 2026-01-13 18:14:36.154571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7446606725'
down_revision: Union[str, Sequence[str], None] = 'bbf3798d3401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'title')
    # ### end Alembic commands ###
