"""update users table

Revision ID: e3a389a85bc5
Revises: 0339f6ed7ef5
Create Date: 2026-01-27 14:21:08.045910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a389a85bc5'
down_revision: Union[str, Sequence[str], None] = '0339f6ed7ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_pin_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_pin_active')
    # ### end Alembic commands ###
