"""update expense-split table

Revision ID: fbb62163468d
Revises: 8702b44c419a
Create Date: 2026-01-13 18:45:00.986105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb62163468d'
down_revision: Union[str, Sequence[str], None] = '8702b44c419a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_splits', sa.Column('member_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('expense_splits_user_id_fkey'), 'expense_splits', type_='foreignkey')
    op.create_foreign_key(None, 'expense_splits', 'group_members', ['member_id'], ['id'])
    op.drop_column('expense_splits', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_splits', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense_splits', type_='foreignkey')
    op.create_foreign_key(op.f('expense_splits_user_id_fkey'), 'expense_splits', 'users', ['user_id'], ['id'])
    op.drop_column('expense_splits', 'member_id')
    # ### end Alembic commands ###
